# Generated by Django 4.1.7 on 2023-03-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_category_women_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Новости :)', 'verbose_name_plural': 'Новости :)'},
        ),
        migrations.AddField(
            model_name='women',
            name='likes_count',
            field=models.IntegerField(null=True),
        ),
    ]
