# Generated by Django 4.1.7 on 2023-03-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_alter_women_options_women_likes_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='likes_count',
            new_name='likes',
        ),
    ]
